version: "3.8"
services:
  dynamodb:
    image: richnorth/dynalite:latest
    ports:
      - 14568:4567
  dynomodb-admin:
    image: aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:4567