aws:
  region: eu-central-1
  dynamodb:
    endpoint: http://localhost:14568

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG